---
- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:
    resource_group: "myResourceGroup"
    location: "eastus"
    vm_name: "myLinuxVM"
    admin_username: "azureuser"
    admin_password: "Password@123"    # Use vault in real environments
    vm_size: "Standard_B1s"           # Free-tier eligible
    image:
      offer: "UbuntuServer"
      publisher: "Canonical"
      sku: "18.04-LTS"
      version: "latest"

  tasks:
    - name: Ensure resource group exists
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"

    - name: Create virtual network
      azure.azcollection.azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}-vnet"
        address_prefixes: "10.0.0.0/16"

    - name: Create subnet
      azure.azcollection.azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}-subnet"
        address_prefix: "10.0.1.0/24"
        virtual_network: "{{ vm_name }}-vnet"

    - name: Create public IP
      azure.azcollection.azure_rm_publicipaddress:
        resource_group: "{{ resource_group }}"
        allocation_method: Static
        name: "{{ vm_name }}-pip"

    - name: Create network interface
      azure.azcollection.azure_rm_networkinterface:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}-nic"
        ip_configurations:
          - name: ipconfig1
            subnet: "{{ vm_name }}-subnet"
            public_ip_address_name: "{{ vm_name }}-pip"

    - name: Create VM
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        vm_size: "{{ vm_size }}"
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        network_interfaces: "{{ vm_name }}-nic"
        image: "{{ image }}"
        state: present
